/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dpiqb;

import com.dpiqb.client.Client;
import com.dpiqb.client.ClientCrudService;
import com.dpiqb.db.DatabaseMigrateService;
import com.dpiqb.db.HibernateUtil;
import org.hibernate.Session;

import java.util.List;

public class App {
  public static void main(String[] args) {
    DatabaseMigrateService.migrateDatabase();
    HibernateUtil util = HibernateUtil.getInstance();
    Session session = util.getSessionFactory().openSession();

    ClientCrudService clientCrudService = new ClientCrudService();
    System.out.println("clientCrudService.readAll() = " + clientCrudService.readAll());
    clientCrudService.deleteById(1L);
    System.out.println("clientCrudService.readAll() = " + clientCrudService.readAll());


//    Client client = new Client();
//    client.setName("Jonathan Show");
//    clientCrudService.create(client);
    session.close();
  }
}
