/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dpiqb;

import com.dpiqb.db.DatabaseMigrateService;

public class App {
  public static void main(String[] args) {
    DatabaseMigrateService.migrateDatabase();
  }
}
